### ISSUE TITLE
invalid nano path

### ISSUE THREAD

**Issue by iamaamir** [simeg/eureka#39]
https://github.com/simeg/eureka/blob/81b6a7e74ddf9d858cc11acc03891750ee03c15e/src/main.rs#L112

the path to nano is invalid or in other words it is not guarantee that nano will available at /usr/bin/nano

![which nano](https://user-images.githubusercontent.com/8420386/50771384-849df800-12b0-11e9-946e-d7a9a1d13ffb.png)

**Comment by simeg** [comment]
Hi @iamaamir. Thanks for reporting this!

On my Mac `nano` lives in `/usr/bin/nano`, hence choosing that path. As I said in #38 the good solution would be to assert what binaries are available at what path before offering the options.

I just create an issue for this: https://github.com/simeg/eureka/issues/40

I chose to go with low priority because it's easy to work around (`--clear-editor`, and the ability to input custom path for editor). PRs are very welcome!

I'm closing this in favor of #40.
